version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['npm','run','start:debug']
    restart: on-failure
    container_name: nest-starter-kit
    environment:
      PORT: 3000
      VIRTUAL_HOST: api.nest-starter-kit.com
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    logging:
      driver: none

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    logging:
      driver: none